version: 2
jobs:
  build:
    working_directory: ~/workspace

    docker:
      - image: circleci/android:api-28-alpha

    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError
        -Dorg.gradle.daemon=false \
        -Dorg.gradle.configureondemand=true \
        -Dorg.gradle.parallel=false \
        -Dorg.gradle.caching=true \
        -Dorg.gradle.workers.max=2 \
        -Dkotlin.compiler.execution.strategy=in-process \
        -Dkotlin.incremental=false"

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew lintStagingDebug app:testStagingDebugUnitTest data:testDebugUnitTest domain:testDebugUnitTest

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results
